# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sunjm/Downloads/xlnt-master/cmake/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sunjm/Downloads/xlnt-master/cmake/pkg-config.pc.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sunjm/Downloads/xlnt-master/source/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sunjm/Downloads/xlnt-master/third-party/libstudxml/CMakeLists.txt))

/Users/sunjm/Downloads/xlnt-master/samples/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/sunjm/Downloads/xlnt-master/samples -B/Users/sunjm/Downloads/xlnt-master/samples
