# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/sunjm/Downloads/xlnt-master/tests/CMakeLists.txt))

/Users/sunjm/Downloads/xlnt-master/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -H/Users/sunjm/Downloads/xlnt-master -B/Users/sunjm/Downloads/xlnt-master
